import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { FormProvider } from "@/providers/FormContext";
import { BudgetSummaryProvider } from "./../providers/BudgetSummaryContext";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Budgeteer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <FormProvider>
          <BudgetSummaryProvider>
            <body className={`${inter.className} bg-slate-50`}>
              <NavBar></NavBar>
              {children}
            </body>
          </BudgetSummaryProvider>
        </FormProvider>
      </SessionWrapper>
    </html>
  );
}
